In [39]:
import pandas as pd
import seaborn as sns

In [48]:
house_data = pd.read_csv("HousePricePrediction.csv")
house_data

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [56]:
house_data.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [101]:
# data processsing and cleaning

# drop Id as it doesnt contribute in price
house_data_copy = house_data.copy()
house_data_copy.drop(["Id"], axis=1, inplace=True)
# replacing SalesPrice with mean
house_data_copy["SalePrice"] = house_data_copy["SalePrice"].fillna(house_data_copy["SalePrice"].mean())

# drop records with null values
house_data_copy = house_data_copy.dropna()
house_data_copy.isnull().sum()

MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

In [102]:
# Data Preprocessing - Encoding
cols = ["MSZoning", "LotConfig","BldgType","Exterior1st"]
house_data_copy = pd.get_dummies(house_data_copy, columns=cols, drop_first=True)

In [104]:
# train test split
from sklearn.model_selection import train_test_split

X = house_data_copy.drop(["SalePrice"], axis=1)
y = house_data_copy["SalePrice"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [106]:
# Train model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [118]:
# predict
y_pred = model.predict(X_test)
y_pred

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2742: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

array([1.93465699e+08, 1.53121168e+08, 1.22655942e+08, 1.09674327e+08,
       1.08663723e+08, 1.30133615e+08, 9.21669752e+07, 8.94601886e+07,
       1.77515809e+08, 1.05480119e+08, 1.33268910e+08, 1.19408821e+08,
       1.23454034e+08, 1.33048686e+08, 1.25980773e+08, 9.89274517e+07,
       1.38782317e+08, 1.20688687e+08, 1.17313868e+08, 1.22174246e+08,
       1.15931011e+08, 2.32940426e+08, 1.85356303e+08, 8.35843515e+07,
       1.33007815e+08, 9.73786464e+07, 1.39042858e+08, 7.44269946e+07,
       1.25146889e+08, 1.25847248e+08, 1.40813193e+08, 1.29167558e+08,
       1.27543742e+08, 1.16999999e+08, 9.38011362e+07, 1.28215797e+08,
       1.17287909e+08, 1.26076806e+08, 6.40624845e+07, 1.09604714e+08,
       1.68506379e+08, 1.03240462e+08, 1.19705788e+08, 1.51981974e+08,
       1.28967513e+08, 1.80918603e+08, 1.44115564e+08, 1.46707758e+08,
       1.52782102e+08, 1.08232182e+08, 1.45894408e+08, 9.32407878e+07,
       1.20077255e+08, 8.80206165e+07, 9.95753452e+07, 1.88411533e+08,
       6.72466222e+07, 1.46900403e+08, 1.29207490e+08, 1.16747864e+08,
       1.38442769e+08, 1.12431268e+08, 1.50716343e+08, 8.61782288e+07,
       1.18560012e+08, 1.39447509e+08, 1.22073415e+08, 1.29622433e+08,
       5.92379101e+07, 1.31900065e+08, 1.06449111e+08, 1.33657790e+08,
       1.23178991e+08, 6.77221033e+07, 1.56163942e+08, 1.19185048e+08,
       9.36843152e+07, 1.26826952e+08, 1.59139600e+08, 1.20466820e+08,
       1.00483679e+08, 1.28315228e+08, 1.07814075e+08, 9.72984895e+07,
       1.03333904e+08, 1.31234982e+08, 1.32724947e+08, 1.28806321e+08,
       1.30309709e+08, 1.39440876e+08, 1.27195292e+08, 1.38260080e+08,
       5.93067649e+07, 1.75510799e+08, 1.18022086e+08, 1.64136449e+08,
       1.03199794e+08, 1.06045292e+08, 1.43394520e+08, 8.99397798e+07,
       1.20312534e+08, 1.56339972e+08, 7.19768759e+07, 1.11145016e+08,
       4.17485034e+08, 1.47986964e+08, 6.71178766e+07, 8.65093808e+07,
       7.53995241e+07, 1.26665062e+08, 1.17860176e+08, 1.16655938e+08,
       1.26779344e+08, 1.00198740e+08, 1.68364710e+08, 8.95123612e+07,
       1.34726105e+08, 1.07954917e+08, 1.30330810e+08, 1.33527701e+08,
       1.33380185e+08, 1.20543910e+08, 1.28125658e+08, 7.19768759e+07,
       1.12414198e+08, 1.01900429e+08, 1.30679680e+08, 1.52364883e+08,
       1.05667786e+08, 1.08485950e+08, 1.37220449e+08, 1.06784373e+08,
       1.27137982e+08, 1.46256753e+08, 6.18435012e+07, 8.28704905e+07,
       1.26362739e+08, 1.29979988e+08, 1.21167799e+08, 1.10279897e+08,
       1.61867699e+08, 9.48230484e+07, 6.91789861e+07, 1.04528209e+08,
       9.67023069e+07, 8.40695143e+07, 1.28501811e+08, 1.23227274e+08,
       1.31513269e+08, 1.62254450e+08, 9.70454899e+07, 1.39477492e+08,
       1.05455785e+08, 1.14900911e+08, 1.04787412e+08, 1.04786719e+08,
       1.34388649e+08, 1.37739183e+08, 1.23680939e+08, 1.06062899e+08,
       2.90244623e+08, 1.85377883e+08, 1.10505128e+08, 1.04706917e+08,
       1.14802598e+08, 1.07232149e+08, 1.05605331e+08, 1.27668156e+08,
       1.04471302e+08, 1.39635699e+08, 1.01605555e+08, 1.47108821e+08,
       9.60546804e+07, 1.11387123e+08, 9.27732431e+07, 8.51104389e+07,
       1.46464575e+08, 1.15727876e+08, 1.08551203e+08, 1.19520365e+08,
       1.12503432e+08, 5.84590486e+07, 1.74261229e+08, 1.02326966e+08,
       1.23852635e+08, 1.04581693e+08, 9.27350537e+07, 1.27415293e+08,
       1.16387097e+08, 1.36343726e+08, 1.45990016e+08, 1.21681574e+08,
       1.21515624e+08, 1.04043939e+08, 8.76569764e+07, 1.22826598e+08,
       7.78141892e+07, 1.12326442e+08, 1.40593735e+08, 1.59178198e+08,
       1.05505025e+08, 1.10623799e+08, 1.97177769e+08, 1.17888668e+08,
       1.48084401e+08, 1.74451110e+08, 1.19327368e+08, 1.26474764e+08,
       1.14595534e+08, 5.92447463e+07, 1.52688831e+08, 8.39123097e+07,
       8.55049297e+07, 1.45092265e+08, 1.24309095e+08, 6.11097869e+07,
       1.73155289e+08, 1.46267631e+08, 1.01956175e+08, 1.53977155e+08,
       1.46690295e+08, 1.23266497e+08, 1.05197523e+08, 1.92456702e+08,
       1.20520151e+08, 1.20540543e+08, 1.09350694e+08, 1.10487648e+08,
       1.39062224e+08, 1.01705248e+08, 9.31305984e+07, 8.41584901e+07,
       1.23592997e+08, 1.20687585e+08, 1.60327749e+08, 1.03055449e+08,
       1.28700466e+08, 1.08686332e+08, 1.19602905e+08, 8.54824990e+07,
       1.08988862e+08, 1.28175772e+08, 1.02497585e+08, 1.42738122e+08,
       1.01427630e+08, 6.87820369e+07, 8.26293984e+07, 1.06222825e+08,
       1.08640265e+08, 1.32203541e+08, 1.49426638e+08, 1.08571824e+08,
       1.34916753e+08, 1.13901482e+08, 1.32046266e+08, 9.90253058e+07,
       1.53369483e+08, 9.70574613e+07, 1.52382453e+08, 1.30548235e+08,
       1.22471357e+08, 4.01070348e+08, 1.70388031e+08, 1.40382573e+08,
       1.18713540e+08, 1.61768320e+08, 1.47501469e+08, 1.24596181e+08,
       1.04409178e+08, 8.79950305e+07, 1.30279415e+08, 1.17531169e+08,
       9.79064575e+07, 1.67678856e+08, 8.55049297e+07, 1.05277749e+08,
       9.32822449e+07, 7.47874345e+07, 6.08691346e+07, 1.56052599e+08,
       1.18641653e+08, 1.20076235e+08, 2.07764113e+08, 1.23764565e+08,
       1.13061647e+08, 1.61552935e+08, 1.62888540e+08, 1.65447863e+08,
       1.31010384e+08, 1.08415379e+08, 1.14015833e+08, 1.37116329e+08,
       1.32029964e+08, 1.23438196e+08, 1.25782043e+08, 1.22161958e+08,
       1.16640940e+08, 1.05048782e+08, 1.98273077e+08, 1.34846294e+08,
       1.20195282e+08, 1.06190335e+08, 1.55930738e+08, 1.09381718e+08,
       1.22855961e+08, 9.51223740e+07, 1.62178557e+08, 9.73794239e+07,
       1.16931394e+08, 1.56433235e+08, 7.89409059e+07, 9.18410054e+07,
       1.52875240e+08, 1.19463195e+08, 1.45233666e+08, 1.13180800e+08,
       1.05898124e+08, 1.02034907e+08, 1.22885103e+08, 1.39517230e+08,
       1.39684164e+08, 1.07172583e+08, 1.26409371e+08, 8.77077052e+07,
       1.58815491e+08, 9.98857700e+07, 1.08150517e+08, 8.78806552e+07,
       8.81931833e+07, 1.08669586e+08, 9.78379161e+07, 1.09460552e+08,
       9.47977172e+07, 8.73858627e+07, 8.12730063e+07, 1.04568407e+08,
       1.32599804e+08, 1.30706895e+08, 1.14389606e+08, 7.74223533e+07,
       1.55857233e+08, 1.07635679e+08, 9.64994099e+07, 1.37693205e+08,
       1.09120698e+08, 2.55973035e+08, 1.93641449e+08, 1.19652000e+08,
       8.08988001e+07, 1.32346365e+08, 1.32560613e+08, 1.11209722e+08,
       9.46610048e+07, 1.15251589e+08, 1.11949528e+08, 1.22853793e+08,
       1.27332633e+08, 9.13010855e+07, 1.15869023e+08, 1.32175929e+08,
       1.07012440e+08, 1.09718368e+08, 8.31333641e+07, 6.76241281e+07,
       1.41639726e+08, 6.50460448e+07, 1.06387669e+08, 1.08982612e+08,
       1.24148631e+08, 9.51852415e+07, 6.18488641e+07, 1.10203667e+08,
       8.15911277e+07, 9.84253488e+07, 1.02756357e+08, 1.28450941e+08,
       1.05216973e+08, 2.25397731e+08, 1.18021573e+08, 1.07916542e+08,
       7.68778770e+07, 1.12437003e+08, 1.18670611e+08, 1.14683010e+08,
       1.51472083e+08, 7.83276750e+07, 1.37446985e+08, 1.29582430e+08,
       1.81713796e+08, 9.27136489e+07, 1.30756138e+08, 1.22896944e+08,
       1.00575502e+08, 1.31892655e+08, 2.04106390e+08, 1.77861746e+08,
       1.81126622e+08, 7.46853059e+07, 1.20916512e+08, 1.25039466e+08,
       1.16571512e+08, 1.57934704e+08, 1.44622227e+08, 1.14480573e+08,
       1.21435908e+08, 1.31446131e+08, 1.16270068e+08, 1.19910544e+08,
       1.15181572e+08, 8.63420148e+07, 1.24044264e+08, 1.08435446e+08,
       1.16216271e+08, 1.05385852e+08, 1.12990098e+08, 1.04856117e+08,
       9.12710485e+07, 1.08456591e+08, 1.06797820e+08, 1.51955515e+08,
       7.04829528e+07, 1.93570285e+08, 1.29726623e+08, 1.39054364e+08,
       1.36344884e+08, 1.18616426e+08, 1.18595881e+08, 1.18443567e+08,
       1.72891678e+08, 6.13312656e+07, 7.11210294e+07, 1.52831032e+08,
       1.75510541e+08, 1.19440609e+08, 1.25800002e+08, 1.22528963e+08,
       1.20807623e+08, 1.82940222e+08, 1.26775273e+08, 8.93903547e+07,
       1.14999752e+08, 1.06069151e+08, 8.51978175e+07, 1.76174988e+08,
       1.20981640e+08, 1.31335791e+08, 1.36500523e+08, 1.21028068e+08,
       1.64476993e+08, 8.06086028e+07, 1.20480731e+08, 1.30444180e+08,
       1.23344750e+08, 1.56446932e+08, 1.29210790e+08, 1.08159532e+08,
       1.03628188e+08, 1.36299117e+08, 1.30586679e+08, 1.30068338e+08,
       1.64453545e+08, 1.40839667e+08, 1.38413408e+08, 1.18457945e+08,
       8.39603277e+07, 1.38406791e+08, 1.20993477e+08, 1.49444144e+08,
       1.46915839e+08, 9.95208848e+07, 1.35619376e+08, 1.64146292e+08,
       1.24839656e+08, 1.51219001e+08, 1.32047421e+08, 6.57978534e+07,
       1.32124206e+08, 1.65035107e+08, 7.73994653e+07, 9.41649794e+07,
       1.08298479e+08, 1.18269933e+08, 1.17999502e+08, 1.28039079e+08,
       1.25491639e+08, 1.65348603e+08, 8.78586159e+07, 1.51404093e+09,
       9.44479507e+07, 1.19338265e+08, 1.34336339e+08, 1.74398388e+08,
       1.34536821e+08, 1.41540877e+08, 1.13638207e+08, 9.58424131e+07,
       1.49123175e+08, 8.91201177e+07, 1.31126162e+08, 1.26513816e+08,
       1.44991864e+08, 1.07295468e+08, 1.04778378e+08, 1.63552465e+08,
       1.15902199e+08, 1.05860460e+08, 1.03317096e+08, 1.64527662e+08,
       1.14439216e+08, 1.38191429e+08, 9.39676110e+07, 1.11550427e+08,
       1.26061225e+08, 1.24878301e+08, 7.02531220e+07, 1.33669169e+08,
       1.49595321e+08, 1.59367759e+08, 1.12046878e+08, 1.49067983e+08,
       1.20810465e+08, 1.28467550e+08, 1.78753469e+08, 1.44787982e+08,
       1.04942178e+08, 1.12236062e+08, 1.39888509e+08, 1.46268277e+08,
       1.99867520e+08, 1.43164840e+08, 2.32938972e+08, 7.40453615e+07,
       1.06064084e+08, 9.03967119e+07, 1.19549912e+08, 9.88542673e+07,
       1.37678884e+08, 1.19889690e+08, 8.29535870e+07, 1.16134507e+08,
       9.03389861e+07, 1.50437356e+08, 1.09403178e+08, 1.62200283e+08,
       7.99406599e+07, 1.18828319e+08, 1.58374195e+08, 6.95878051e+07,
       1.09192426e+08, 1.02404913e+08, 1.26208163e+08, 1.21991672e+08,
       1.19685966e+08, 1.23847154e+08, 1.08115413e+08, 1.29378206e+08,
       1.20156924e+08, 1.31430654e+08, 1.26523946e+08, 1.11608525e+08,
       6.74453010e+07, 9.65109592e+07, 7.88084284e+07, 1.07083832e+08,
       1.11728421e+08, 9.61080386e+07, 1.08777818e+08, 8.40695143e+07,
       1.25762131e+08, 1.02095242e+08, 1.20964594e+08, 9.86947171e+07,
       1.27309776e+08, 1.42473535e+08, 9.51845040e+07, 1.27401060e+08,
       1.19668858e+08, 2.28869655e+08, 1.08103560e+08, 1.32274818e+08,
       1.11299294e+08, 1.28166422e+08, 8.89373855e+07])

In [120]:
# Model Evaluation
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Mean abs:",mean_absolute_percentage_error(y_test, y_pred))

R2 Score: -5499908.49115419
MAE: 124776308.25198348
RMSE: 141608794.5260428
Mean abs: 727.2259436915813

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2742: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(