In [ ]:
# Q2. Start by loading the TITANIC dataset.
# A. Display only columns:
# Name
# Sex
# Age
# Fare
# Survived

# B. Select passengers who:
# Are female
# Fare > 30

# C. Group by Pclass and compute:
# Survival rate
# Average Fare
# Average Age

In [22]:
import pandas as pd

In [24]:
# A. Display only columns:
# Name
# Sex
# Age
# Fare
# Survived
df = pd.read_csv("Titanic-Dataset.csv")
df
df[["Name", "Sex", "Age", "Fare", "Survived"]]

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,13.0000,0
887,"Graham, Miss. Margaret Edith",female,19.0,30.0000,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.4500,0
889,"Behr, Mr. Karl Howell",male,26.0,30.0000,1
890,"Dooley, Mr. Patrick",male,32.0,7.7500,0

In [34]:
# B. Select passengers who:
# Are female
# Fare > 30
# df[(df["Sex"] == "female") & (df["Fare"] > 30)]
df.query("Sex == 'female' & Fare > 30")[["Sex", "Fare"]]

        Sex      Fare
1    female   71.2833
3    female   53.1000
9    female   30.0708
25   female   31.3875
31   female  146.5208
..      ...       ...
853  female   39.4000
856  female  164.8667
863  female   69.5500
871  female   52.5542
879  female   83.1583

[113 rows x 2 columns]

In [43]:
# C. Group by Pclass and compute:
# Survival rate
# Average Fare
# Average Age

df.groupby("Pclass").agg(
    survival_rate = ("Survived","mean"),
    avg_fare = ("Fare","mean"),
    avg_age = ("Age","mean")
)

        survival_rate   avg_fare    avg_age
Pclass
1            0.629630  84.154687  38.233441
2            0.472826  20.662183  29.877630
3            0.242363  13.675550  25.140620